### ISSUE TITLE
network path isn't liked

### ISSUE THREAD

**Issue by Ragornette** [vinavfx/stock_manager#3]
Hello,
just installed and tried it and I get these errors:
```
Traceback (most recent call last):
  File "C:\Program Files\Nuke15.0v4\python310.zip\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Nuke15.0v4\python310.zip\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users/Ragornette/.nuke\stock_manager\src\indexing_panel.py", line 183, in refresh_indexs_thread
    indexing.to_index(self.finished_index,
  File "C:\Users/Ragornette/.nuke\stock_manager\src\indexing.py", line 45, in to_index
    for stock in get_stocks_from_folder(folder):
  File "C:\Users/Ragornette/.nuke\stock_manager\src\indexing.py", line 325, in get_stocks_from_folder
    textures, sequences = separate_texture_and_sequence(
  File "C:\Users/Ragornette/.nuke\stock_manager\src\indexing.py", line 376, in separate_texture_and_sequence
    for texture in get_sequence(sequence, [first, last]):
  File "C:\Users/Ragornette/.nuke\stock_manager\nuke_util\media_util.py", line 152, in get_sequence
    number = int(f.split(pre, 1)[1][:-len(suffix)])
ValueError: empty separator
```

It's on win10. I also tried with 13.2v8.
Same errors.
The path of the footages is on a nas.
x:\VIDEO or \\192.168.1.3\footages\VIDEO
Same issues.
Then I copied one folder on a local disk and it was working.
Any clue?
Thanks

**Comment by vinavfx** [comment]
that file no longer exists, now you can only index via terminal:
cd ~/.nuke/stock_manager/scripts
python3 indexing.py
